spring.application.name = spring-web-mvc

spring.web.resources.static-locations=classpath:/static/

#spring.mustache.prefix=classpath:/templates/
#spring.mustache.suffix=.mustache
#spring.mustache.charset=UTF-8
#spring.mustache.check-template-location=true

#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

server.port=8080
server.shutdown=graceful


