spring.application.name=spring-data-mongo

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=schooldb
#spring.data.mongodb.username=wulf
#spring.data.mongodb.password=wulf123
spring.data.mongodb.auto-index-creation=true