spring.application.name = library-mini

spring.datasource.url=jdbc:mysql://localhost:3306/library_db
spring.datasource.username=wulf
spring.datasource.password=wulf123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema/create_users_table.sql,\
                                 classpath:db/schema/create_books_table.sql,\
                                 classpath:db/schema/create_loans_table.sql
spring.sql.init.data-locations=classpath:db/data/insert_users_data.sql,\
                               classpath:db/data/insert_books_data.sql,\
                               classpath:db/data/insert_loans_data.sql
spring.sql.init.platform=mysql
spring.sql.init.continue-on-error=false

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=3600
spring.mvc.static-path-pattern=/assets/**

spring.mustache.prefix=classpath:/templates/
spring.mustache.suffix=.mustache
spring.mustache.cache=false
spring.mustache.servlet.content-type=text/html;charset=UTF-8
spring.mustache.enabled=true
spring.mustache.check-template-location=true