spring.application.name = core

app.prop.name = Swayam
app.prop.developer = true
app.prop.age = 24

app.basic.name = Swayam
app.basic.developer = true
app.basic.age = 24
app.basic.marks = 90.2

#app.complex.additional-info = some additional info
app.complex.external-servers = server1,server2,server3
app.complex.internal-servers[0] = server4
app.complex.internal-servers[1] = server5
app.complex.internal-servers[2] = server6
app.complex.stats.ram = 8
app.complex.stats.ssd = 256
app.complex.timeout = 10s
app.complex.file-size = 100KB
app.complex.domain = https://api.wulfcodes.io